name: CI-CD-JH
on:
  push:
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Obtendo o código
      uses: actions/checkout@v4.1.7
    - name: Autenticação no Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build da imagem docker
      uses: docker/build-push-action@v6
      with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            joaohfm/aula-primeira-pipeline:v${{ github.run_number }}
            joaohfm/aula-primeira-pipeline:latest
  CD-Homolog:
    needs: [CI]
    uses: joaohfm86/primeira-pipeline-cicd/.github/workflows/deploy.yml@main
    with:
      manifests: k8s/deployment.yaml
      images: joaohfm/aula-primeira-pipeline:v${{ github.run_number }}
      environment: homologacao
    secrets: inherit
  Teste-ambiente:
    needs: [CD-Homolog]
    runs-on: ubuntu-latest
    environment: homologacao
    steps:
      - name: Fake Teste
        run: echo "Fake Teste de ambiente ${{ vars.APP_NAMESPACE }}"  

  CD-Producao:
    needs: [Teste-ambiente]
    uses: joaohfm86/primeira-pipeline-cicd/.github/workflows/deploy.yml@main
    with:
      manifests: k8s/deployment.yaml
      images: joaohfm/aula-primeira-pipeline:v${{ github.run_number }}
      environment: producao
    secrets: inherit