name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Obtendo o código
      uses: actions/checkout@v4.1.7
    - name: Autenticação no Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build da imagem docker
      uses: docker/build-push-action@v6
      with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            joaohfm/aula-primeira-pipeline:v${{ github.run_number }}
            joaohfm/aula-primeira-pipeline:latest
