name: CI-CD-JH
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Obtendo o código
      uses: actions/checkout@v4.1.7
    - name: Autenticação no Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build da imagem docker
      uses: docker/build-push-action@v6
      with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            joaohfm/aula-primeira-pipeline:v${{ github.run_number }}
            joaohfm/aula-primeira-pipeline:latest
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true
    - name: Install gke-gcloud-auth-plugin
      run: |
        sudo apt-get install apt-transport-https ca-certificates gnupg
        sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin
    - name: Obtendo o código
      uses: actions/checkout@v4.1.7
    - name: Configuração de contexto do kubernetes
      uses: azure/k8s-set-context@v4
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.K8S_CONFIG }}
    - name: Execução do Manifesto
      uses: Azure/k8s-deploy@v5
      with:
        manifests: |
          ./k8s/deployment.yaml
        images: |
          joaohfm/aula-primeira-pipeline:v${{ github.run_number }}